export default {
  //Honor
  honor: [
    {
      img: require("@/assets/pic/HonorIcons/house.svg"),
      chinese: "整套房源",
      description: "你可以獨享整套樹屋。",
    },
    {
      img: require("@/assets/pic/HonorIcons/Star.svg"),
      chinese: "資深房東",
      description: "Putu在其他房源獲得了300則評價。",
    },
    {
      img: require("@/assets/pic/HonorIcons/clean.svg"),
      chinese: "乾淨整潔",
      description: "近期有房客稱讚此房源一塵不染。",
    },
    {
      img: require("@/assets/pic/HonorIcons/Achievement.svg"),
      chinese: "超讚房東",
      description:
        "超讚房東是經驗豐富、評價超高的房東，致力為房客提供最棒的住宿體驗。",
    },
    {
      img: require("@/assets/pic/HonorIcons/key.svg"),
      chinese: "超棒入住體驗",
      description: "最近有95%的房客給予入住流程5星評分。",
    },
    {
      img: require("@/assets/pic/HonorIcons/calander.svg"),
      chinese: "48小時內可免費取消",
      description: "",
    },
    // {
    //   //img: require("@/assets/pic/HonorIcons/communicative.svg"),
    //   img:"",
    //   chinese: "溝通順暢",
    //   description: "溝通順暢Benedetto的溝通能力近期獲得100%的房客給予5星評分。",
    // },
    {
      img: require("@/assets/pic/HonorIcons/DeepCleaning.svg"),
      chinese: "深度清潔",
      description: "此房東承諾遵守 Airbnb 的深度清潔五步驟。",
    },
    {
      img: require("@/assets/pic/HonorIcons/SelfCheck-in.svg"),
      chinese: "自助入住",
      description: "使用密碼鑰匙盒自助入住",
    },
    {
      img: require("@/assets/pic/HonorIcons/GreatLocation.svg"),
      chinese: "絕佳位置",
      description: "最近有100%的房客給予房源位置5星評分。",
    },
    {
      img: require("@/assets/pic/HonorIcons/popular.svg"),
      chinese: "無線網路",
      description: "房客常搜尋這項熱門設備",
    },
    {
      img: require("@/assets/pic/HonorIcons/popular.svg"),
      chinese: "游泳池",
      description: "房客常搜尋這項熱門設備",
    },
    {
      img: require("@/assets/pic/HonorIcons/popular.svg"),
      chinese: "洗衣機",
      description: "房客常搜尋這項熱門設備",
    },
    {
      img: require("@/assets/pic/HonorIcons/popular.svg"),
      chinese: "建築物內免費停車",
      description: "房客常搜尋這項熱門設備",
    },
    {
      img: require("@/assets/pic/HonorIcons/popular.svg"),
      chinese: "可攜帶寵物",
      description: "房客常搜尋這項熱門設備",
    },
    {
      img: require("@/assets/pic/HonorIcons/popular.svg"),
      chinese: "建築物內免費停車",
      description: "房客常搜尋這項熱門設備",
    }
  ],
  //設施
  facilities: [
    {
      name: "HairDryer",
      chinese: "吹風機",
      mapping: 106,
      img: require("@/assets/pic/FacilityIcons/HairDryer.svg"),
    },
    {
      name: "Heating",
      chinese: "暖氣",
      mapping: 503,
      img: require("@/assets/pic/FacilityIcons/Heating.svg"),
    },
    {
      name: "CarbonMonoxideAlarm",
      chinese: "一氧化碳警報器",
      mapping: 601,
      img: require("@/assets/pic/FacilityIcons/CarbonMonoxideAlarm.svg"),
    },
    {
      name: "AirConditioner",
      chinese: "空調設備",
      mapping: 501,
      img: require("@/assets/pic/FacilityIcons/AirConditioner.svg"),
    },
    {
      name: "Washer",
      chinese: "洗衣機",
      mapping: 601,
      img: require("@/assets/pic/FacilityIcons/Washer.svg"),
    },
    {
      name: "LongTermStaysAllowed",
      chinese: "可長期住宿",
      mapping: 1203,
      img: require("@/assets/pic/FacilityIcons/LongTermStaysAllowed.svg"),
    },
    {
      name: "Breakfast",
      chinese: "早餐",
      mapping: 1201,
      img: require("@/assets/pic/FacilityIcons/Breakfast.svg"),
    },
    {
      name: "LuggageDropOffAllowed",
      chinese: "可存放行李",
      mapping: 1204,
      img: require("@/assets/pic/FacilityIcons/LuggageDropOffAllowed.svg"),
    },
    {
      name: "PaidParkingOnPremises",
      chinese: "建築物內有收費停車位",
      mapping: 1108,
      img: require("@/assets/pic/FacilityIcons/PaidParkingOnPremises.svg"),
    },
    {
      name: "Jacuzzi",
      chinese: "按摩浴缸",
      mapping: 1106,
      img: require("@/assets/pic/FacilityIcons/Jacuzzi.svg"),
    },
    {
      name: "FreeBuildingParking",
      chinese: "建築物內免費停車",
      mapping: 1103,
      img: require("@/assets/pic/FacilityIcons/FreeBuildingParking.svg"),
    },
    {
      name: "BBQ",
      chinese: "烤肉區",
      mapping: 1002,
      img: require("@/assets/pic/FacilityIcons/BBQ.svg"),
    },
    {
      name: "OutdoorFurniture",
      chinese: "戶外家具",
      mapping: 1010,
      img: require("@/assets/pic/FacilityIcons/OutdoorFurniture.svg"),
    },
    {
      name: "Backyard",
      chinese: "後院",
      mapping: 1001,
      img: require("@/assets/pic/FacilityIcons/Backyard.svg"),
    },
    {
      name: "Patio",
      chinese: "庭院",
      mapping: 1012,
      img: require("@/assets/pic/FacilityIcons/Patio.svg"),
    },
    {
      name: "PrivateEntrance",
      chinese: "獨立入口",
      mapping: 904,
      img: require("@/assets/pic/FacilityIcons/PrivateEntrance.svg"),
    },
    {
      name: "CoffeeMaker",
      chinese: "咖啡機",
      mapping: 806,
      img: require("@/assets/pic/FacilityIcons/CoffeeMaker.svg"),
    },
    {
      name: "Oven",
      chinese: "烤箱",
      mapping: 816,
      img: require("@/assets/pic/FacilityIcons/Oven.svg"),
    },
    {
      name: "Stove",
      chinese: "爐子",
      mapping: 819,
      img: require("@/assets/pic/FacilityIcons/Stove.svg"),
    },
    {
      name: "Microwave",
      chinese: "微波爐",
      mapping: 814,
      img: require("@/assets/pic/FacilityIcons/Microwave.svg"),
    },
    {
      name: "Refrigerator",
      chinese: "冰箱",
      mapping: 817,
      img: require("@/assets/pic/FacilityIcons/Refrigerator.svg"),
    },
    {
      name: "CookingBasics",
      chinese: "基本廚具",
      mapping: 807,
      img: require("@/assets/pic/FacilityIcons/CookingBasics.svg"),
    },
    {
      name: "WorkSpace",
      chinese: "專門工作空間",
      mapping: 701,
      img: require("@/assets/pic/FacilityIcons/WorkSpace.svg"),
    },
    {
      name: "Wifi",
      chinese: "無線網路",
      mapping: 703,
      img: require("@/assets/pic/FacilityIcons/Wifi.svg"),
    },
    {
      name: "FirstAidKit",
      chinese: "急救包",
      mapping: 603,
      img: require("@/assets/pic/FacilityIcons/FirstAidKit.svg"),
    },
    {
      name: "FireExtinguisher",
      chinese: "滅火器",
      mapping: 602,
      img: require("@/assets/pic/FacilityIcons/FireExtinguisher.svg"),
    },
    {
      name: "SmokeAlarm",
      chinese: "煙霧警報器",
      mapping: 605,
      //img: require("@/assets/pic/FacilityIcons/SmokeAlarm.svg"),
      img:""
    },
    {
      name: "Television",
      chinese: "電視",
      mapping: 310,
      img: require("@/assets/pic/FacilityIcons/Television.svg"),
    },
    {
      name: "Iron",
      chinese: "熨斗",
      mapping: 208,
      img: require("@/assets/pic/FacilityIcons/Iron.svg"),
    },
    {
      name: "ExtraBedding",
      chinese: "額外的枕頭與毛毯",
      mapping: 206,
      img: require("@/assets/pic/FacilityIcons/ExtraBedding.svg"),
    },
    {
      name: "BedLinens",
      chinese: "床單",
      mapping: 202,
      img: require("@/assets/pic/FacilityIcons/BedLinens.svg"),
    },
    {
      name: "Hanger",
      chinese: "衣架",
      mapping: 207,
      img: require("@/assets/pic/FacilityIcons/Hanger.svg"),
    },
    {
      name: "Essentials",
      chinese: "生活必需品",
      mapping: 1003,
      img: require("@/assets/pic/FacilityIcons/Essentials.svg"),
    },
    {
      name: "HotWater",
      chinese: "熱水",
      mapping: 107,
      img: require("@/assets/pic/FacilityIcons/HotWater.svg"),
    },
    {
      name: "Shampoo",
      chinese: "洗髮露",
      mapping: 109,
      img: require("@/assets/pic/FacilityIcons/Shampoo.svg"),
    },
    {
      name: "Kitchen",
      chinese: "廚房",
      mapping: 813,
      //img: require("@/assets/pic/FacilityIcons/Kitchen.svg"),
      img:""
    },
    {
      name: "CleaningProducts",
      chinese: "清潔產品",
      mapping: 104,
      img: require("@/assets/pic/FacilityIcons/CleaningProducts.svg"),
    },
    {
      name: "Dryer",
      chinese: "乾衣機",
      mapping: 204,
      img: require("@/assets/pic/FacilityIcons/Dryer.svg"),
    },
    {
      name: "Toys",
      chinese: "童書與玩具",
      mapping: 407,
      img: require("@/assets/pic/FacilityIcons/Toys.svg"),
    },
    {
      name: "BabySafetyGates",
      chinese: "嬰兒安全門欄",
      mapping: 403,
      img: require("@/assets/pic/FacilityIcons/BabySafetyGates.svg"),
    },
    {
      name: "IndoorFireplace",
      chinese: "室內壁爐",
      mapping: 504,
      img: require("@/assets/pic/FacilityIcons/IndoorFireplace.svg"),
    },
    {
      name: "DishesAndSilverware",
      chinese: "盤子和餐具",
      mapping: 809,
      img: require("@/assets/pic/FacilityIcons/DishesAndSilverware.svg"),
    },
    {
      name: "FreeStreetParking",
      chinese: "路邊有免費停車",
      mapping: 1104,
      img: require("@/assets/pic/FacilityIcons/FreeStreetParking.svg"),
    },
    {
      name: "Pool",
      chinese: "游泳池",
      mapping: 1109,
      img: require("@/assets/pic/FacilityIcons/Pool.svg"),
    },
    {
      name: "Dishwasher",
      chinese: "洗碗機",
      mapping: 810,
      img: require("@/assets/pic/FacilityIcons/Dishwasher.svg"),
    },
    {
      name: "LakeAccess",
      chinese: "直達湖畔",
      mapping: 902,
      img: require("@/assets/pic/FacilityIcons/LakeAccess.svg"),
    },
    {
      name: "BodySoap",
      chinese: "沐浴露",
      mapping: 103,
      img: require("@/assets/pic/FacilityIcons/BodySoap.svg"),
    },
    {
      name: "Tub",
      chinese: "浴缸",
      mapping: 101,
      img: require("@/assets/pic/FacilityIcons/Tub.svg"),
    },
    {
      name: "Conditioner",
      chinese: "潤髮乳",
      mapping: 105,
      img: require("@/assets/pic/FacilityIcons/Conditioner.svg"),
    },
    {
      name: "BodySoap",
      chinese: "沐浴乳",
      mapping: 103,
      img: require("@/assets/pic/FacilityIcons/BodySoap.svg"),
    },
    {
      name: "Crib",
      chinese: "嬰兒床",
      mapping: 409,
      img: require("@/assets/pic/FacilityIcons/Crib.svg"),
    },
    {
      name: "HighChair",
      chinese: "兒童高腳椅",
      mapping: 411,
      img: require("@/assets/pic/FacilityIcons/HighChair.svg"),
    },
    {
      name: "CeilingFan",
      chinese: "吊扇",
      mapping: 502,
      img: require("@/assets/pic/FacilityIcons/CeilingFan.svg"),
    },
    {
      name: "Freezer",
      chinese: "冷凍庫",
      mapping: 811,
      img: require("@/assets/pic/FacilityIcons/Freezer.svg"),
    },
    {
      name: "HotWaterKettle",
      chinese: "熱水壺",
      mapping: 812,
      img: require("@/assets/pic/FacilityIcons/HotWaterKettle.svg"),
    },
    {
      name: "WineGlasses",
      chinese: "葡萄酒杯",
      mapping: 822,
      img: require("@/assets/pic/FacilityIcons/WineGlasses.svg"),
    },
    {
      name: "BreadMaker",
      chinese: "烤麵包機",
      mapping: 803,
      img: require("@/assets/pic/FacilityIcons/BreadMaker.svg"),
    },
    {
      name: "BakingSheet",
      chinese: "烤盤",
      mapping: 801,
      img: require("@/assets/pic/FacilityIcons/BakingSheet.svg"),
    },
    {
      name: "BarbecueUtensils",
      chinese: "燒烤用具",
      mapping: 802,
      img: require("@/assets/pic/FacilityIcons/BarbecueUtensils.svg"),
    },
    {
      name: "Coffee",
      chinese: "咖啡",
      mapping: 805,
      img: require("@/assets/pic/FacilityIcons/Coffee.svg"),
    },
    {
      name: "DiningTable",
      chinese: "餐桌",
      mapping: 808,
      img: require("@/assets/pic/FacilityIcons/DiningTable.svg"),
    },
    {
      name: "Waterfront",
      chinese: "緊鄰水岸",
      mapping: 907,
      img: require("@/assets/pic/FacilityIcons/Waterfront.svg"),
    },
    {
      name: "Hammock",
      chinese: "吊床",
      mapping: 1007,
      img: require("@/assets/pic/FacilityIcons/Hammock.svg"),
    },
    {
      name: "MosquitoNet",
      chinese: "蚊帳",
      mapping: 209,
      img: require("@/assets/pic/FacilityIcons/MosquitoNet.svg"),
    },
    {
      name: "BoardGames",
      chinese: "桌遊",
      mapping: 405,
      img: require("@/assets/pic/FacilityIcons/BoardGames.svg"),
    },
    {
      name: "PortableFans",
      chinese: "移動式電扇",
      mapping: 505,
      img: require("@/assets/pic/FacilityIcons/PortableFans.svg"),
    },
    {
      name: "FirePit",
      chinese: "火坑",
      mapping: 1006,
      img: require("@/assets/pic/FacilityIcons/FirePit.svg"),
    },
    {
      name: "Bikes",
      chinese: "自行車",
      mapping: 1004,
      img: require("@/assets/pic/FacilityIcons/Bikes.svg"),
    },
    {
      name: "LockOnBedroom",
      chinese: "帶鎖的臥室",
      mapping: 604,
      img: require("@/assets/pic/FacilityIcons/LockOnBedroom.svg"),
    },
    {
      name: "PrivateLivingRoom",
      chinese: "獨立客廳",
      mapping: 1110,
      img: require("@/assets/pic/FacilityIcons/PrivateLivingRoom.svg"),
    },
    {
      name: "PocketWifi",
      chinese: "可攜式WIFI",
      mapping: 702,
      img: require("@/assets/pic/FacilityIcons/PocketWifi.svg"),
    },
    {
      name: "MiniFridge",
      chinese: "小冰箱",
      mapping: 815,
      img: require("@/assets/pic/FacilityIcons/MiniFridge.svg"),
    },
    {
      name: "LaundromatNearby",
      chinese: "附近有自助洗衣店",
      mapping: 903,
    //   img: require("@/assets/pic/FacilityIcons/LaundromatNearby.svg"),
      img:""
    },
    {
      name: "Bidet",
      chinese: "坐浴盆",
      mapping: 102,
      img: require("@/assets/pic/FacilityIcons/Bidet.svg"),
    },
    {
      name: "OutDoorShower",
      chinese: "戶外沐浴空間",
      mapping: 108,
      img: require("@/assets/pic/FacilityIcons/OutDoorShower.svg"),
    },
    {
      name: "ClothingStorage",
      chinese: "衣櫥",
      mapping: 203,
      img: require("@/assets/pic/FacilityIcons/ClothingStorage.svg"),
    },
    {
      name: "Clotheshorse",
      chinese: "曬衣架(竿)",
      mapping: 205,
      img: "",
    },
    {
      name: "Curtain",
      chinese: "窗簾",
      mapping: 210,
      img: require("@/assets/pic/FacilityIcons/Curtain.svg"),
    },
    {
      name: "Books",
      chinese: "書",
      mapping: 301,
      img: require("@/assets/pic/FacilityIcons/Books.svg"),
    },
    {
      name: "Ethernet",
      chinese: "網路線",
      mapping: 302,
      img: require("@/assets/pic/FacilityIcons/Ethernet.svg"),
    },
    {
      name: "ExerciseEquipment",
      chinese: "運動器材",
      mapping: 303,
      img: require("@/assets/pic/FacilityIcons/ExerciseEquipment.svg"),
    },
    {
      name: "GameHost",
      chinese: "遊戲主機",
      mapping: 304,
      img: require("@/assets/pic/FacilityIcons/GameHost.svg"),
    },
    {
      name: "Piano",
      chinese: "鋼琴",
      mapping: 305,
      img: require("@/assets/pic/FacilityIcons/Piano.svg"),
    },
    {
      name: "PingPangTable",
      chinese: "乒乓球桌",
      mapping: 306,
      img: "",
    },
    {
      name: "PoolTable",
      chinese: "撞球桌",
      mapping: 307,
      img: "",
    },
    {
      name: "RecordPlayer",
      chinese: "黑膠唱片機",
      mapping: 308,
      img: "",
    },
    {
      name: "Audio",
      chinese: "音響",
      mapping: 309,
      img: require("@/assets/pic/FacilityIcons/Audio.svg"),
    },
    {
      name: "BabyBath",
      chinese: "嬰兒浴盆",
      mapping: 401,
      img: require("@/assets/pic/FacilityIcons/BabyBath.svg"),
    },
    {
      name: "BabyMonitor",
      chinese: "嬰兒監視器",
      mapping: 402,
      img: "",
    },
    {
      name: "BabysitterRecommendations",
      chinese: "臨時保母推薦",
      mapping: 404,
      img: require("@/assets/pic/FacilityIcons/BabysitterRecommendations.svg"),
    },
    {
      name: "ChangingTable",
      chinese: "尿布台",
      mapping: 406,
      img: require("@/assets/pic/FacilityIcons/ChangingTable.svg"),
    },
    {
      name: "ChildrenDinnerware",
      chinese: "兒童餐桌",
      mapping: 408,
      img: "",
    },
    {
      name: "FireplaceGuards",
      chinese: "壁爐護欄",
      mapping: 410,
      img: require("@/assets/pic/FacilityIcons/FireplaceGuards.svg"),
    },
    {
      name: "OutletCovers",
      chinese: "插座蓋",
      mapping: 412,
      img: require("@/assets/pic/FacilityIcons/OutletCovers.svg"),
    },
    {
      name: "TravelCrib",
      chinese: "旅行用嬰兒床",
      mapping: 413,
      img: require("@/assets/pic/FacilityIcons/TravelCrib.svg"),
    },
    {
      name: "TableCornerGuards",
      chinese: "桌腳防護",
      mapping: 414,
      img: require("@/assets/pic/FacilityIcons/TableCornerGuards.svg"),
    },
    {
      name: "WindowGuards",
      chinese: "窗柵",
      mapping: 415,
      img: require("@/assets/pic/FacilityIcons/WindowGuards.svg"),
    },
    {
      name: "Blender",
      chinese: "調理機",
      mapping: 804,
      img: require("@/assets/pic/FacilityIcons/Blender.svg"),
    },
    {
      name: "RiceMaker",
      chinese: "電鍋",
      mapping: 818,
      img: require("@/assets/pic/FacilityIcons/RiceMaker.svg"),
    },
    {
      name: "Toaster",
      chinese: "烤麵包機",
      mapping: 820,
      img: require("@/assets/pic/FacilityIcons/Toaster.svg"),
    },
    {
      name: "TrashCompactor",
      chinese: "壓縮式垃圾桶",
      mapping: 821,
      img: "",
    },
    {
      name: "BeachAccess",
      chinese: "直達海灘",
      mapping: 901,
      img: require("@/assets/pic/FacilityIcons/BeachAccess.svg"),
    },
    {
      name: "ResortAccess",
      chinese: "度假村入場證",
      mapping: 905,
      img: require("@/assets/pic/FacilityIcons/ResortAccess.svg"),
    },
    {
      name: "SkiOut",
      chinese: "無須搭乘交通工具即可前往滑雪場",
      mapping: 906,
      img: require("@/assets/pic/FacilityIcons/SkiOut.svg"),
    },
    {
      name: "BeachEssentials",
      chinese: "沙灘必備物品",
      mapping: 1003,
      img: require("@/assets/pic/FacilityIcons/BeachEssentials.svg"),
    },
    {
      name: "BoatSlip",
      chinese: "船梯",
      mapping: 1005,
      img: "",
    },
    {
      name: "Kayak",
      chinese: "小輕艇",
      mapping: 1008,
      img: require("@/assets/pic/FacilityIcons/Kayak.svg"),
    },
    {
      name: "OutdoorDiningArea",
      chinese: "室外用餐區",
      mapping: 1009,
      img: require("@/assets/pic/FacilityIcons/OutdoorDiningArea.svg"),
    },
    {
      name: "OutdoorKitchen",
      chinese: "戶外廚房",
      mapping: 1011,
      img: require("@/assets/pic/FacilityIcons/OutdoorKitchen.svg"),
    },
    {
      name: "Elevator",
      chinese: "電梯",
      mapping: 1101,
      img: require("@/assets/pic/FacilityIcons/Elevator.svg"),
    },
    {
      name: "EVCharger",
      chinese: "電動汽車充電設備",
      mapping: 1102,
      img: require("@/assets/pic/FacilityIcons/EVCharger.svg"),
    },
    {
      name: "Gym",
      chinese: "健身房",
      mapping: 1105,
      img: require("@/assets/pic/FacilityIcons/Gym.svg"),
    },
    {
      name: "PaidParkingOffPremises",
      chinese: "建築物範圍外有收費停車",
      mapping: 1107,
      img: require("@/assets/pic/FacilityIcons/PaidParkingOffPremises.svg"),
    },
    {
      name: "Sauna",
      chinese: "三溫暖",
      mapping: 1111,
      img: require("@/assets/pic/FacilityIcons/Sauna.svg"),
    },
    {
      name: "SingleLevelHome",
      chinese: "獨立房屋",
      mapping: 1112,
      img: require("@/assets/pic/FacilityIcons/SingleLevelHome.svg"),
    },
    {
      name: "CleaningBeforeCheckout",
      chinese: "退房前打掃",
      mapping: 1202,
      img: require("@/assets/pic/FacilityIcons/CleaningBeforeCheckout.svg"),
    },
  ],
  //房屋守則
  houseRules: [
    {
      chinese: "入住時間",
      img: require("@/assets/pic/HouseRulesIcons/time.svg"),
    },
    {
      chinese: "退房時間",
      img: require("@/assets/pic/HouseRulesIcons/time.svg"),
    },
    {
      chinese: "禁止吸煙",
      img: require("@/assets/pic/HouseRulesIcons/noSmoke.svg"),
    },
    {
      chinese: "允許攜帶寵物",
      img: require("@/assets/pic/HouseRulesIcons/pet.svg"),
    },
    {
      chinese: "自助入住方式：密碼鑰匙盒",
      img: require("@/assets/pic/HouseRulesIcons/SelfCheck-inMethod.svg"),
    },
    {
      chinese: "自助入住方式：大樓員工",
      img: require("@/assets/pic/HouseRulesIcons/SelfCheck-inMethod.svg"),
    },
    {
      chinese: "自助入住方式：鍵盤鎖",
      img: require("@/assets/pic/HouseRulesIcons/SelfCheck-inMethod.svg"),
    },
    {
      chinese: "不允許攜帶寵物",
      img: require("@/assets/pic/HouseRulesIcons/noPet.svg"),
    },
    {
      chinese: "不適合兒童和嬰幼兒",
      img: require("@/assets/pic/HouseRulesIcons/noKid.svg"),
    },
    {
      chinese: "不允許舉辦聚會和活動",
      img: require("@/assets/pic/HouseRulesIcons/noEvent.svg"),
    },
    {
      chinese: "允許抽煙",
      img: "",
    },
    //依此類推
  ],
  //健康與安全
  safety: [
    {
      chinese: "適用 Airbnb 社交距離指南和其他防疫指南",
      img: require("@/assets/pic/SafetyIcons/EpidemicPrevention.svg"),
    },
    {
      chinese: "未回報是否有安裝一氧化碳警報器",
      img: "",
    },
    {
      chinese: "監視攝影機／攝錄裝置",
      img: "",
    },
    {
      chinese: "煙霧警報器",
      img: require("@/assets/pic/SafetyIcons/SmokeAlarm.svg"),
    },
    {
      chinese: "承諾遵守 Airbnb 的深度清潔流程。 顯示更多內容",
      img: "",
    },
    {
      chinese:
        "在新冠肺炎疫情大流行期間，所有用戶都必須閱讀和遵守 Airbnb 的社交距離指南和其他防疫指南。",
      img: require("@/assets/pic/SafetyIcons/EpidemicPrevention.svg"),
    },
    {
      chinese: "未安裝煙霧警報器",
      img: "",
    },
    {
      chinese:
        "監視攝影機／攝錄裝置",
      img: "",
    },
    {
      chinese: "附近的湖泊、河流、其他水域",
      img: "",
    },
    {
      chinese: "無門鎖的泳池／按摩浴池",
      img: "",
    },
    {
      chinese: "房源內有寵物",
      img: "",
    },
    {
      chinese:
        "未回報是否有安裝一氧化碳警報器 — 房東未告知房源內是否有安裝一氧化碳警報器。 我們建議您在旅行時隨身攜帶可攜式偵測器。",
      img: "",
    },
    {
      chinese:
        "未回報是否有安裝煙霧警報器 — 房東未告知房源內是否有安裝煙霧警報器。 我們建議您在旅行時隨身攜帶可攜式偵測器。 ",
      img: "",
    },
    {
      chinese: "一氧化碳警報器",
      img: require("@/assets/pic/SafetyIcons/SmokeAlarm.svg"),
    },
    {
      chinese: "需要走樓梯",
      img: require("@/assets/pic/SafetyIcons/Stair.svg"),
    },
    {
      chinese: "受限的設備與服務",
      img: "",
    },
    {
      chinese: "可能會有噪音",
      img: "",
    },
    {
      chinese: "需要共用部分空間",
      img: "",
    },
    {
      chinese: "攀爬或遊樂設施",
      img: "",
    },
    {
      chinese: "押金",
      img: require("@/assets/pic/SafetyIcons/Deposit.svg"),
    },
  ],
  //退訂政策
  unBooking: [
    { name: "unBooking", title: "彈性", detail: "在入住日1天前取消預訂，可獲得全額退款" },
    { name: "unBooking", title: "彈性或不可退款", detail: "除了彈性退訂政策外，您還可以提供不可退款選項：房客雖然會少付10%的費用，不過無論何時對方取消預訂，您都能保留全數收款。" },
    { name: "unBooking", title: "中等", detail: "在入住日5天前取消預訂，可獲得全額退款" },
    { name: "unBooking", title: "中等或不可退款", detail: "除了中等退訂政策外，您還可以提供不可退款選項：房客雖然會少付10%的費用，不過無論何時對方取消預訂，您都能保留全數收款。" },
    { name: "unBooking", title: "稍嚴", detail: "最晚在入住前 30 天取消可拿回全額退款。如果在入住前 30 天預訂，並在預訂後 48 小時內且入住前至少 14 天取消，即可拿回全額退款。在此之後，最晚在入住前 7 天取消可拿回 50% 退款。在這之後取消則不予退款。" },
    { name: "unBooking", title: "較嚴格或不可退款", detail: "除了《較嚴格退訂政策》外，你也可以提供不可退款選項：房客雖然會少付 10% 費用，但若取消預訂，你就能保留全數收款。" },
    { name: "unBooking", title: "嚴格", detail: "針對14天之後的預訂，若房客在預訂後48小時內取消，可以獲得全額退款。提早入住日期7天前取消預訂，可獲得50%退款。旅程開始前7天內取消，則無法退款。" },
    { name: "unBooking", title: "嚴格或不可退款", detail: "除了嚴格退訂政策外，您還可以提供不可退款選項：房客雖然會少付10%的費用，不過萬一對方取消預訂，您就能保留全數收款。" }
  ],
  //Todo-假照片
  pictures:[
        "https://images.pexels.com/photos/584399/living-room-couch-interior-room-584399.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/545034/pexels-photo-545034.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/6970068/pexels-photo-6970068.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/6758770/pexels-photo-6758770.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/5998055/pexels-photo-5998055.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7319337/pexels-photo-7319337.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/4857757/pexels-photo-4857757.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/6969777/pexels-photo-6969777.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/4532831/pexels-photo-4532831.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/5998023/pexels-photo-5998023.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/3119180/pexels-photo-3119180.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/6480707/pexels-photo-6480707.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/6707628/pexels-photo-6707628.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7932264/pexels-photo-7932264.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/5849392/pexels-photo-5849392.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7147284/pexels-photo-7147284.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7147363/pexels-photo-7147363.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7166558/pexels-photo-7166558.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/2062431/pexels-photo-2062431.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7147366/pexels-photo-7147366.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7147298/pexels-photo-7147298.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7166559/pexels-photo-7166559.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7166554/pexels-photo-7166554.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/2724749/pexels-photo-2724749.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/1918291/pexels-photo-1918291.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/7166625/pexels-photo-7166625.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/189333/pexels-photo-189333.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/269218/pexels-photo-269218.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/380768/pexels-photo-380768.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/756076/pexels-photo-756076.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/2635038/pexels-photo-2635038.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/2631746/pexels-photo-2631746.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/4050318/pexels-photo-4050318.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/2598638/pexels-photo-2598638.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/271618/pexels-photo-271618.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/545012/pexels-photo-545012.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/1080721/pexels-photo-1080721.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/276583/pexels-photo-276583.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/383568/pexels-photo-383568.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/354939/pexels-photo-354939.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/877971/pexels-photo-877971.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/210265/pexels-photo-210265.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
        "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  ],
  //Todo-假大頭貼照片
  portraits:[
    "https://images.pexels.com/photos/3042160/pexels-photo-3042160.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "https://images.pexels.com/photos/3328072/pexels-photo-3328072.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    "https://images.pexels.com/photos/3190334/pexels-photo-3190334.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/2748239/pexels-photo-2748239.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/3823495/pexels-photo-3823495.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/2269872/pexels-photo-2269872.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/1526814/pexels-photo-1526814.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/1493111/pexels-photo-1493111.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/1317712/pexels-photo-1317712.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    "https://images.pexels.com/photos/1520760/pexels-photo-1520760.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940"
  ],
};
