name: default ci cd

on:
  push:
    branches:
      - master
      - Develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/peace920902/index.json -n "private-packages" --store-password-in-clear-text -u peace920902 -p ${{ secrets.PACKAGE_TOKEN }}
          dotnet restore      
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: dotnet test -c Release --no-build --verbosity normal
      - name: Publish
        run: dotnet publish -c Release --no-build
      - name: docker build
        run: docker build . -t ghcr.io/airelax/airelax
      - name: docker login
        run: docker login ghcr.io -u airelax -p ${{ secrets.PACKAGE_TOKEN }}
      - name: docker push
        run: docker push ghcr.io/airelax/airelax:latest
